// Generated by gencpp from file pkg_timedomain_uwb/msg_timedomain_uwb.msg
// DO NOT EDIT!


#ifndef PKG_TIMEDOMAIN_UWB_MESSAGE_MSG_TIMEDOMAIN_UWB_H
#define PKG_TIMEDOMAIN_UWB_MESSAGE_MSG_TIMEDOMAIN_UWB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pkg_timedomain_uwb
{
template <class ContainerAllocator>
struct msg_timedomain_uwb_
{
  typedef msg_timedomain_uwb_<ContainerAllocator> Type;

  msg_timedomain_uwb_()
    : header()
    , id_module_uwb(0)
    , range(0.0)
    , range_err(0.0)  {
    }
  msg_timedomain_uwb_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id_module_uwb(0)
    , range(0.0)
    , range_err(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _id_module_uwb_type;
  _id_module_uwb_type id_module_uwb;

   typedef double _range_type;
  _range_type range;

   typedef double _range_err_type;
  _range_err_type range_err;




  typedef boost::shared_ptr< ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator> const> ConstPtr;

}; // struct msg_timedomain_uwb_

typedef ::pkg_timedomain_uwb::msg_timedomain_uwb_<std::allocator<void> > msg_timedomain_uwb;

typedef boost::shared_ptr< ::pkg_timedomain_uwb::msg_timedomain_uwb > msg_timedomain_uwbPtr;
typedef boost::shared_ptr< ::pkg_timedomain_uwb::msg_timedomain_uwb const> msg_timedomain_uwbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pkg_timedomain_uwb

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'pkg_timedomain_uwb': ['/home/york1/catkin_ws/src/vai_uav0/pkg_timedomain_uwb/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5832270dc2da80beb97f2d958efffd99";
  }

  static const char* value(const ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5832270dc2da80beULL;
  static const uint64_t static_value2 = 0xb97f2d958efffd99ULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_timedomain_uwb/msg_timedomain_uwb";
  }

  static const char* value(const ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header  header\n\
uint32  id_module_uwb\n\
float64 range\n\
float64 range_err\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id_module_uwb);
      stream.next(m.range);
      stream.next(m.range_err);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_timedomain_uwb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_timedomain_uwb::msg_timedomain_uwb_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id_module_uwb: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id_module_uwb);
    s << indent << "range: ";
    Printer<double>::stream(s, indent + "  ", v.range);
    s << indent << "range_err: ";
    Printer<double>::stream(s, indent + "  ", v.range_err);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_TIMEDOMAIN_UWB_MESSAGE_MSG_TIMEDOMAIN_UWB_H
